version: 0.2  
  
phases:
  install: 
    runtime-versions: 
        java: openjdk8
  pre_build:  
    commands: 
      - echo Logging in to Amazon ECR...  
      - aws --version  
      - docker version  
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)  
      - REPOSITORY_URI=572909725151.dkr.ecr.eu-west-1.amazonaws.com/smsys-backend  
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)  
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - START_DATE=$(date -d @$CODEBUILD_START_TIME)
      - echo "{\"buildId\":\""$CODEBUILD_BUILD_ID"\", \"startTime\":\""$START_DATE"\", \"initiator\":\""$CODEBUILD_INITIATOR"\", \"buildNumber\":\""$CODEBUILD_BUILD_NUMBER"\"}" > version.json
      - cp $CODEBUILD_SRC_DIR/version.json $CODEBUILD_SRC_DIR/src/main/resources/
      - cat $CODEBUILD_SRC_DIR/src/main/resources/version.json
  build:  
    commands:  
      - echo Build started on `date`  
      - echo Building the Docker image...            
      - docker build -t $REPOSITORY_URI:latest .  
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG  
  post_build:  
    commands:  
      - echo Build completed on `date`  
      - echo Pushing the Docker images...  
      - docker push $REPOSITORY_URI:latest 
      - echo Writing image definitions file...  
      - printf '[{"name":"smsys-backend","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json 
      - cat imagedefinitions.json 
artifacts:  
    files:  
      - imagedefinitions.json