
server:
  servlet:
    context-path: "/api/v1/"
  port: 9000


logging:
  level:
    org.springframework: ERROR

spring:
  profiles:
    active: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
 # datasource:
 #   platform: org.hibernate.dialect.H2Dialect
 #   url: jdbc:h2:mem:testdb
 #   username: sa
 #   password: password
 #   driverClassName: org.h2.Driver
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/edumago"
    username: "postgres"
    password: "edumago"
    driverClassName: org.postgresql.Driver



# H2
  spring.h2.console.enabled: true
  spring.h2.console.path: /h2