
server:
  servlet:
    context-path: "/api/v1/"
  port: 9000


spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://localhost:5433/edumago"
    username: "postgres"
    password: 99032
    initialization-mode: always
    platform: postgres
  jpa:
    - properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    - main:
        banner-mode: off


logging:
  level:
    org.springframework: ERROR

---


server:
  servlet:
    context-path: "/api/v1/"
  port: 9000


spring:
  profiles:
    active: prod
  datasource:
    url: "jdbc:postgresql://smsys-database.c770b9ur1mtc.eu-west-1.rds.amazonaws.com:5448/edumago"
    username: "edumago"
    password: "!*!2019Edumago"
    initialization-mode: always
    platform: postgres
  jpa:
    - properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    - main:
        banner-mode: off


logging:
  level:
    org.springframework: ERROR