
server:
  servlet:
    context-path: "/api/v1/"
  port: 9000


logging:
  level:
    org.springframework: ERROR


spring:
  profiles:
    active: prod
  datasource:
    url: "jdbc:postgresql://smsys-database.c770b9ur1mtc.eu-west-1.rds.amazonaws.com:5448/edumago"
    username: "edumago"
    password: "!*!2019Edumago"
    initialization-mode: always
    platform: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update